version: "3.3"
services:
  text-generation-webui:
    image: 522185657747.dkr.ecr.us-west-2.amazonaws.com/textgen
    build:
      context: .
      args:
        # specify which cuda version your card supports: https://developer.nvidia.com/cuda-gpus
        TORCH_CUDA_ARCH_LIST: ${TORCH_CUDA_ARCH_LIST}
        WEBUI_VERSION: ${WEBUI_VERSION}
    #environment:
      #- CLI_ARGS=--model RWKV-4-Pile-3B-20221110-ctx4096.pth --listen --no-stream --extensions openai
    env_file: .env
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
      - "${HOST_API_PORT}:${CONTAINER_API_PORT}"
      - "${HOST_API_STREAM_PORT}:${CONTAINER_API_STREAM_PORT}"
      - 8080:5001
    stdin_open: true
    tty: true
    volumes:
      - ./characters:/app/characters
      - ./extensions:/app/extensions
      - ./loras:/app/loras
      - ./models:/app/models
      - ./presets:/app/presets
      - ./prompts:/app/prompts
      - ./softprompts:/app/softprompts
      - ./training:/app/training
      - /home/ec2-user:/home/ec2-user
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]

# aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 522185657747.dkr.ecr.us-west-2.amazonaws.com
# docker push 522185657747.dkr.ecr.us-west-2.amazonaws.com/textgen
